config/routes.rb
CurbApi::Application.routes.draw do

  mount_griddler
  
  namespace :developers do
    devise_for :developers, module: "developers/devise", path: "developer"
    root 'dashboard#index'
    resources :apps
    get 'api' => 'api#index'
    get 'api/:action' => 'api#index', as: "api_doc"
  end

  namespace :api do
    namespace :v3 do
      get 'agents/find'
      get 'agents' => "agents#index"
      get 'service/index'
      get 'organization/showing_report' => "organization#showing_report", as: :api_v3_organization_showing_report
      resources :agents do
      	resources :showings, only: [:index]
      end
      resources :users   
      resources :showings do
        member do
          post 'claim'
          post 'start'
          post 'end'
          post 'self_start'
        end
      end
      namespace :radius do
        get 'client_token' => "braintree#client_token"
        post 'subscriptions' => "braintree#subscriptions"
        devise_for :radius_users
        resources :users do
          resources :emergency_contacts
        end
      end
    end
  end

  get 'main/home'
  get 'pages/check_email' => 'pages#check_email'
  get 'pages/reset_password_success' => 'pages#reset_password_success'

  namespace :admin do
    root "dashboard#index"
    resources :settings do
    end

    resources :brokerages

    namespace :mls do
      get 'map'
      get 'listings'
    end
  end

  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'

  get "brokerage_dashboard/showings/real_time" => "brokerage_dashboard/showings#real_time", as: "real_time_brokerage_dashboard_showings_path"

  shallow do
    namespace :brokerage_dashboard do
      get '/' => 'dashboard#index'
      resources :brokerage do
        resources :users do
          member do
            get 'reset_password'
          end
          resources :showings do
            resources :sightings
          end
        end
      end
    end
  end

  # resources :showings
  get 's/:id' => 'showings#show', :as => "hidden_showing"


  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations" }



  devise_scope :user do
    post 'registrations' => 'registrations#create', :as => 'register'
    post 'sessions' => 'sessions#create', :as => 'login'
    put 'sessions' => 'sessions#update', :as => 'edit_session'
    delete 'sessions' => 'sessions#destroy', :as => 'logout'
    put 'registrations' => 'registrations#edit', :as => 'edit'
  end

  namespace :api do
    namespace :v1 do
      resources :regions, except: [:new, :edit]
      resources :brokerages, except: [:new, :edit]
      resources :zips#, except: [:new, :edit]
      resources :profiles
      resources :eligible_agents
      resources :showings, except: [:new, :edit]
      resources :leads
      resources :agents#, except: [:new, :edit]
      resources :listings, except: [:new, :edit]
      resources :nearby_agents
      resources :mls
      resources :get_listings
      resources :dev_tokens
    end

    namespace :v2 do
      resources :regions, except: [:new, :edit]
      resources :brokerages, except: [:new, :edit]
      resources :zips#, except: [:new, :edit]
      resources :profiles
      resources :eligible_agents
      resources :showings#, except: [:new, :edit]
      resources :leads
      resources :agents#, except: [:new, :edit]
      resources :listings, except: [:new, :edit]
      resources :nearby_agents
      resources :mls
      resources :get_listings
      resources :dev_tokens
      resources :emergency_contacts
      post 'sightings/heartbeat'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'


  # You can have the root of your site routed with "root"
  root 'main#home'


end

app/controllers/api/v3/users_controller.rb
class Api::V3::UsersController < Api::V3::ServiceController

  def update
    @user = User.find(params[:id])

    if @user.update(profile_params)
      render json: @user
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  private
  
  def profile_params
    params.permit(:player_id)
  end 

end

app/controllers/brokerage_dashboard/dashboard_controller.rb
class BrokerageDashboard::DashboardController < ApplicationController
	before_filter :authenticate_user!
  before_filter :set_brokerage
  layout 'dashboard'
  
  def index
    #get brokerage showings for today
    today=Time.zone.today
    start_date=today.beginning_of_day
    week_start_date=today.beginning_of_week
    month_start_date=today.beginning_of_month
    end_date=today.end_of_day
    
    @showings=@brokerage.showings_request.for_range(start_date, end_date).waiting#.includes(:sightings)
    @showings_this_week=@brokerage.showings.for_range(week_start_date, end_date)
    @showings_this_month=@brokerage.showings.for_range(month_start_date, end_date)
    
    @active_showings = @brokerage.showings.active.reject{|showing|showing.sightings.empty?}
  end
  
  private
  def set_brokerage
    if current_user.brokerage
      @brokerage = current_user.brokerage
    else
      redirect_to root_path, notice: 'This user does not belong to a brokerage.'
    end
  end

  # def index
  #   # if current_user.office_admin == "true"
  #     @users = User.all
  #     @agents = User.where(brokerage_id: current_user.brokerage_id)
  #     @live_agents = Agent.where(brokerage_id: current_user.brokerage_id)
  #     @brokerage = Brokerage.find(current_user.brokerage_id)
  #     @showings = Showing.all
  #
  #     #@buyers = User.where(id: )
  #
  #     # @showing_now = Array.new
  #     # Showing.where(status: nil).each do |showing|
  #     #   if User.find(showing.agent_id).exists?
  #     #     agent = User.find(showing.agent_id)
  #     #   else
  #     #     agent = 100000000000000000
  #     #   end
  #
  #     #   if agent.brokerage_id == @brokerage.id
  #     #     @showing_now << agent
  #     #   end
  #     # end
  #
  #   # else
  #   #   redirect_to login_path
  #   # end
  #     # @json = @live_agents.to_gmaps4rails
  #    #      @markers = @live_agents.to_gmaps4rails
  # end
  #
  # def show
  #   @agent = User.find(params[:id])
  #   @available = Agent.where(user_id: @agent.id).any?
  # end
end

app/controllers/brokerage_dashboard/showings_controller.rb
class BrokerageDashboard::ShowingsController < BrokerageDashboard::DashboardController
  before_action :set_showing, only: [:show, :edit, :update, :destroy]

  def real_time
    @active_showings = @brokerage.showings.active.reject{|showing|showing.sightings.empty?}
  end
  
  # GET /showings
  # GET /showings.json
  def index
    @search = params[:search]
    @showings = @brokerage.showings_request.search_param(@search, params[:status_state_search]).page(params[:page]).order("created_at DESC")
  end

  # GET /showings/1
  # GET /showings/1.json
  def show
    @user= current_user
    @sightings = @showing.sightings
    # @history = CurbCall::SafetyRadius::History.new(@showing.id, nil).all
  end

  # GET /showings/new
  def new
    @showing = Showing.new
  end

  # GET /showings/1/edit
  def edit
  end

  # POST /showings
  # POST /showings.json
  def create
    @showing = Showing.new(showing_params)

    respond_to do |format|
      if @showing.save
        format.html { redirect_to @showing, notice: 'Showing was successfully created.' }
        format.json { render :show, status: :created, location: @showing }
      else
        format.html { render :new }
        format.json { render json: @showing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /showings/1
  # PATCH/PUT /showings/1.json
  def update
    respond_to do |format|
      if @showing.update(showing_params)
        format.html { redirect_to @showing, notice: 'Showing was successfully updated.' }
        format.json { render :show, status: :ok, location: @showing }
      else
        format.html { render :edit }
        format.json { render json: @showing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /showings/1
  # DELETE /showings/1.json
  def destroy
    @showing.destroy
    respond_to do |format|
      format.html { redirect_to showings_url, notice: 'Showing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_showing
      @showing = Showing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def showing_params
      params.require(:showing).permit(:agent_id, :lead_id, :address, :buyer_name, :agent_name, :buyer_id, :status, :mls_num)
    end
end

app/controllers/brokerage_dashboard/users_controller.rb
class BrokerageDashboard::UsersController < BrokerageDashboard::DashboardController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
    @brokerage = current_user.brokerage
    @agents = @brokerage.users.page(params[:page])
  
  end
  
  def show

    user_id = params[:id]
    @user = User.find(user_id)
    @brokerage = current_user.brokerage
    @showings = Showing.where(showing_owner_id: user_id)
  end
  
  # GET /users/new
  def new
    @user = User.new
    @form_brokerage=@brokerage#hack
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
    @form_brokerage=nil#hack
  end
  
  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.brokerage=@brokerage

    respond_to do |format|
      if @user.save
        @user.active_for_authentication?
        format.html { redirect_to brokerage_dashboard_user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        @form_brokerage=@brokerage#hack
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

    @user = User.find(params[:id])
    
    respond_to do |format|
      if @user.update(update_user_params)
        format.html { redirect_to brokerage_dashboard_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to brokerage_dashboard_brokerage_users_path(@brokerage), notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  def showing_show
    brokerage_id = params[:id]
    user_id = params[:user_id]
    showing_id = params[:showing_id]
    
    @brokerage = Brokerage.find(brokerage_id)
    @user = User.find(user_id)
    @showing = Showing.find(showing_id)
    @sightings = @showing.sightings
    
  end
  
  
  def reset_password
    @user = User.find(params[:id])
    token = @user.send_reset_password_instructions
    
    respond_to do |format|
      format.html {redirect_to brokerage_dashboard_user_path(@user), notice: "Welcome email sent to user."}
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, emergency_contacts_attributes:[:name, :phone, :email, :id])
    end
    def update_user_params
      params.require(:user).permit(:name, :email, emergency_contacts_attributes:[:name, :phone, :email, :id, :_destroy])
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  protected

  def after_resetting_password_path_for(resource)
     "/pages/reset_password_success"
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    "/pages/check_email"
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]
  def after_sign_in_path_for(user)
    brokerage_dashboard_path
  end
  
  layout "user_devise"
  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/brokerage_dashboard/users/_form.html.haml
.row.form-wrapper
  / left column
  .col-md-9.with-sidebar
    = nested_form_for [:brokerage_dashboard, @form_brokerage, @user], html: { class: "form-horizontal"} do |f|
      - if @user.errors.any?
        #error_explanation
          %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
          %ul
            - @user.errors.full_messages.each do |msg|
              %li= msg
      
      .form-group
        %label.col-md-2.control-label{:for => "inputName1"} Name
        .col-md-8
          =f.text_field :name, class: "form-control",:placeholder => "Name", :type => "text"
      .form-group
        %label.col-md-2.control-label{:for => "inputEmail1"} Email
        .col-md-8
          =f.text_field :email, class: "form-control",:placeholder => "Email", :type => "text"
      -if !@user.persisted?
        .form-group
          %label.col-md-2.control-label{:for => "inputPassword1"} Password
          .col-md-8
            =f.text_field :password, class: "form-control",:placeholder => "Password  ", :type => "password", :autocomplete=>"false"
      -if @user.persisted?      
        %h3 Emergency Contacts
        =f.fields_for :emergency_contacts do |builder|
          .form-group
            %label.col-md-2.control-label{:for => "inputName1"} Name
            .col-md-8
              =builder.text_field :name, class: "form-control",:placeholder => "Name", :type => "text"
          .form-group
            %label.col-md-2.control-label{:for => "inputName1"} Phone
            .col-md-8
              =builder.text_field :phone, class: "form-control",:placeholder => "Phone", :type => "text"
          .form-group
            %label.col-md-2.control-label{:for => "inputName1"} Email
            .col-md-8
              =builder.email_field :email, class: "form-control",:placeholder => "Email", :type => "text"
          .form-group
            %label.col-md-2.control-label{:for => "inputName1"} Remove Contact
            .col-md-8
              = builder.link_to_remove "Remove this Contact"
          
        = f.link_to_add "Add a Contact", :emergency_contacts

      .form-group
        .col-md-offset-2.col-md-8
          = f.submit 'Save', class: "btn-glow primary"

app/views/brokerage_dashboard/users/edit.html.haml
#pad-wrapper.new-user
  .row.header
    .col-md-12
      %h3 Editing User
  = render 'form'

  = link_to 'Show', brokerage_dashboard_user_path(@user)
  \|
  = link_to 'Back', brokerage_dashboard_brokerage_users_path(@brokerage)

app/views/brokerage_dashboard/users/index.html.haml
.users-list
  .row.header
    %h3 Users
    .col-md-10.col-sm-12.col-xs-12.pull-right
      %input.col-md-5.search{:placeholder => "Type a user's name...", :type => "text"}/
      / custom popup filter
      / styles are located in css/elements.css
      / script that enables this dropdown is located in js/theme.js
      .ui-dropdown
        .head{"data-toggle" => "tooltip", :title => "Click me!"}
          Filter users
          %i.arrow-down
        .dialog
          .pointer
            .arrow
            .arrow_border
          .body
            %p.title
              Show users where:
            .form
              %select
                %option Name
                %option Email
                %option Number of orders
                %option Signed up
                %option Last seen
              %select
                %option is equal to
                %option is not equal to
                %option is greater than
                %option starts with
                %option contains
              %input.form-control{:type => "text"}/
              %a.btn-flat.small Add filter
      =link_to "NEW USER +", new_brokerage_dashboard_brokerage_user_path, class: "btn-flat success pull-right"\
  / Users table
  .row
    .col-md-12
      %table.table.table-hover
        %thead
          %tr
            %th.col-md-4.sortable
              Name
            %th.col-md-3.sortable
              %span.line>
              Signed up
            %th.col-md-2.sortable
              %span.line>
              Showings
            %th.col-md-3.sortable.align-right
              %span.line>
              Email
        %tbody
          / row
          -@agents.each do |agent|
            %tr
              %td
                =image_tag image_url(agent), class: "img-circle avatar hidden-phone"
                =link_to agent.name, brokerage_dashboard_user_path( agent), class: "name"
                %span.subtext 
                  Last Showing:
                  = last_showing(agent)
              %td
                =agent.created_at.strftime("%a %b %d %Y")
              %td
                =agent.showings.count
              %td.align-right
                %a{:href => "#"}=agent.email
  = paginate @agents
  / end users table

app/views/brokerage_dashboard/users/new.html.haml
#pad-wrapper.new-user
  .row.header
    .col-md-12
      %h3 Create a new user
  = render 'form'

= link_to 'Back', brokerage_dashboard_brokerage_users_path

app/views/brokerage_dashboard/users/show.html.haml
#pad-wrapper.user-profile
  / header
  .row.header
    .col-md-1
      =image_tag image_url(@user), class: "avatar img img-circle m-t-xs img-responsive"
    .col-md-7
      %h3.name=@user.name
      %span.area 
        =@user.showings.count
        Showing(s)
    %a.btn-flat.icon.pull-right.delete-user{"href"=> brokerage_dashboard_user_path(@user),"data-confirm" => "Are you sure?","data-placement" => "top","data-method" => "delete", "data-toggle" => "tooltip", :title => "Delete user"}
      %i.icon-trash
    =link_to "Edit this person", edit_brokerage_dashboard_user_path(@user), class: "btn-flat icon large pull-right edit"  
    =link_to "Reset Password", reset_password_brokerage_dashboard_user_path(@user), class: "btn-flat icon large pull-right edit"  
    
  .row.profile
    / bio, new note & orders column
    .col-md-9.bio
      .profile-box
        / biography
        .col-md-12.section
          %h6 Biography
          %p=@user.try(:profile).try(:bio)
        %h6 Recent Showings
        %br/
        / recent orders table
        %table.table.table-hover
          %thead
            %tr
              %th.col-md-2
                ID
              %th.col-md-3
                %span.line
                Address
              %th.col-md-3
                %span.line
                Buyer
              %th.col-md-3
                %span.line
                Date
          %tbody
            / row
            -@showings.each do |showing|
              %tr
                %td
                  =link_to "##{showing.id}", brokerage_dashboard_showing_path(showing)
                %td
                  =showing.address
                %td
                  =showing.buyer_name
                %td
                  =showing.created_at.strftime("%a %b %d %Y")


        %h6 Emergency Contacts
        %br/
        / emergency contacts list
        %table.table.table-hover
          %thead
            %tr
              %th.col-md-3
                %span.line
                Name
              %th.col-md-3
                %span.line
                Phone
              %th.col-md-3
                %span.line
                Email
          %tbody
            / row
            -@user.emergency_contacts.each do |contact|
              %tr
                %td
                  =contact.name
                %td
                  =contact.phone
                %td
                  =contact.email
                  
        / new comment form
        .col-md-12.section.comment
          %h6 Add a quick note
          %p Add a note about this user to keep a history of your interactions.
          %textarea
          %a{:href => "#"} Attach files
          .col-md-12.submit-box.pull-right
            %input.btn-glow.primary{:type => "submit", :value => "Add Note"}/
            %span OR
            %input.reset{:type => "reset", :value => "Cancel"}/
    / side address column
    .col-md-3.col-xs-12.address.pull-right
      %h6 Contact Info
      %ul
        -if @user.try(:profile).try(:phone)
          %li.ico-li
            %i.ico-phone=@user.try(:profile).try(:phone)
        %li.ico-li
          %i.ico-mail
          %a{:href => "#"}=@user.email