config/routes.rb
CurbApi::Application.routes.draw do

  mount_griddler
  
  namespace :developers do
    devise_for :developers, module: "developers/devise", path: "developer"
    root 'dashboard#index'
    resources :apps
    get 'api' => 'api#index'
    get 'api/:action' => 'api#index', as: "api_doc"
  end

  namespace :api do
    namespace :v3 do
      get 'agents/find'
      get 'agents' => "agents#index"
      get 'service/index'
      get 'organization/showing_report' => "organization#showing_report", as: :api_v3_organization_showing_report
      resources :agents do
      	resources :showings, only: [:index]
      end
      resources :users   
      resources :showings do
        member do
          post 'claim'
          post 'start'
          post 'end'
          post 'self_start'
        end
      end
      namespace :radius do
        get 'client_token' => "braintree#client_token"
        post 'subscriptions' => "braintree#subscriptions"
        devise_for :radius_users
        resources :users do
          resources :emergency_contacts
        end
      end
    end
  end

  get 'main/home'
  get 'pages/check_email' => 'pages#check_email'
  get 'pages/reset_password_success' => 'pages#reset_password_success'

  namespace :admin do
    root "dashboard#index"
    resources :settings do
    end

    resources :brokerages

    namespace :mls do
      get 'map'
      get 'listings'
    end
  end

  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'

  get "brokerage_dashboard/showings/real_time" => "brokerage_dashboard/showings#real_time", as: "real_time_brokerage_dashboard_showings_path"

  shallow do
    namespace :brokerage_dashboard do
      get '/' => 'dashboard#index'
      resources :brokerage do
        resources :users do
          member do
            get 'reset_password'
          end
          resources :showings do
            resources :sightings
          end
        end
      end
    end
  end

  # resources :showings
  get 's/:id' => 'showings#show', :as => "hidden_showing"


  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations" }



  devise_scope :user do
    post 'registrations' => 'registrations#create', :as => 'register'
    post 'sessions' => 'sessions#create', :as => 'login'
    put 'sessions' => 'sessions#update', :as => 'edit_session'
    delete 'sessions' => 'sessions#destroy', :as => 'logout'
    put 'registrations' => 'registrations#edit', :as => 'edit'
  end

  namespace :api do
    namespace :v1 do
      resources :regions, except: [:new, :edit]
      resources :brokerages, except: [:new, :edit]
      resources :zips#, except: [:new, :edit]
      resources :profiles
      resources :eligible_agents
      resources :showings, except: [:new, :edit]
      resources :leads
      resources :agents#, except: [:new, :edit]
      resources :listings, except: [:new, :edit]
      resources :nearby_agents
      resources :mls
      resources :get_listings
      resources :dev_tokens
    end

    namespace :v2 do
      resources :regions, except: [:new, :edit]
      resources :brokerages, except: [:new, :edit]
      resources :zips#, except: [:new, :edit]
      resources :profiles
      resources :eligible_agents
      resources :showings#, except: [:new, :edit]
      resources :leads
      resources :agents#, except: [:new, :edit]
      resources :listings, except: [:new, :edit]
      resources :nearby_agents
      resources :mls
      resources :get_listings
      resources :dev_tokens
      resources :emergency_contacts
      post 'sightings/heartbeat'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'


  # You can have the root of your site routed with "root"
  root 'main#home'


end

app/models/setting.rb
class Setting

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :key, :val

  validates :key, :presence => true
  validates :val, :presence => true

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def id
    self.key
  end
  
  def update(attribs)
    val = attribs[:val]
    CurbCall::Config[self.key]=val
  end

  def persisted?
    true
  end
  
  def self.find(key)
    val = CurbCall::Config[key]
    Setting.new key: key, val:val
  end

end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::AdminController
  def index
    
    files = [CurbCall::Messages::Types::AgentDangerMessage::SETTINGS, 
      CurbCall::Messages::Types::ShowingStartedMessage::SETTINGS,
      CurbCall::Messages::Types::ShowingCompletedMessage::SETTINGS,
      CurbCall::Messages::Types::NoAgentsAvailMessage::SETTINGS,
      CurbCall::Twillio::SmsService::SETTINGS,
      CurbCall::SafetyRadius::Base::SETTINGS,
      CurbCall::Messages::EmailMessage::SETTINGS,
      CurbCall::Messages::Types::AgentPanicMessage::SETTINGS,
      CurbCall::DispatchService::Dispatcher::SETTINGS]
      
    settings = files.reduce({}, :merge)
    @settings = {}
    
    settings.each do |k,v|
      val = CurbCall::Config[v]
      @settings[k] = val
    end
    
    @settings
    
  end
  
  def show
  end
  
  def edit
    @setting = Setting.find(params[:id])
  end
  
  def update
    @setting = Setting.find(params[:id])
    
    respond_to do |format|
      if @setting.update(params[:setting])
        format.html { redirect_to admin_settings_path, notice: 'Setting was successfully updated.' }
      else
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end
  
end

app/helpers/admin/settings_helper.rb
module Admin::SettingsHelper
end

app/views/admin/settings/_form.html.haml
.row.form-wrapper
  / left column
  .col-md-9.with-sidebar
    = form_for [:admin, @setting], html: { class: "form-horizontal"} do |f|
      - if @setting.errors.any?
        #error_explanation
          %h2= "#{pluralize(@setting.errors.count, "error")} prohibited this setting from being saved:"
          %ul
            - @setting.errors.full_messages.each do |msg|
              %li= msg
      
      .form-group
        %label.col-md-2.control-label{:for => "inputName1"}=@setting.key
        .col-md-8
          =f.text_field :val, class: "form-control",:placeholder => "Value", :type => "text"


      .form-group
        .col-md-offset-2.col-md-8
          = f.submit 'Save', class: "btn-glow primary"

app/views/admin/settings/edit.html.haml
%h1 Editing setting

= render 'form'

= link_to 'Show',admin_setting_path([nil,@setting])
\|
= link_to 'Back', admin_settings_path

app/views/admin/settings/index.html.haml
.table-wrapper.products-table.section
  .row.head
    .col-md-12
      %h4 Global App Settigns
  .row.filter-block
    .pull-right
      %a.btn-flat.success.new-product + Add setting
  .row
    %table.table.table-hover
      %thead
        %tr
          %th.col-md-3
            %input{:type => "checkbox"}/
            Key
          %th.col-md-3
            %span.line>
            Value
          %th.col-md-3
      %tbody
        -@settings.each do |k,v|
          %tr
            %td
              %input{:type => "checkbox"}/
              %a.name{:href => "#"}=k
            %td.description=v
            %td
              %ul.actions
                %li
                  =link_to "Edit", edit_admin_setting_path(k) 
                %li.last
                  %a{:href => "#"} Delete