config/routes.rb
CurbApi::Application.routes.draw do

  mount_griddler
  
  namespace :developers do
    devise_for :developers, module: "developers/devise", path: "developer"
    root 'dashboard#index'
    resources :apps
    get 'api' => 'api#index'
    get 'api/:action' => 'api#index', as: "api_doc"
  end

  namespace :api do
    namespace :v3 do
      get 'agents/find'
      get 'agents' => "agents#index"
      get 'service/index'
      get 'organization/showing_report' => "organization#showing_report", as: :api_v3_organization_showing_report
      resources :agents do
      	resources :showings, only: [:index]
      end
      resources :users   
      resources :showings do
        member do
          post 'claim'
          post 'start'
          post 'end'
          post 'self_start'
        end
      end
      namespace :radius do
        get 'client_token' => "braintree#client_token"
        post 'subscriptions' => "braintree#subscriptions"
        devise_for :radius_users
        resources :users do
          resources :emergency_contacts
        end
      end
    end
  end

  get 'main/home'
  get 'pages/check_email' => 'pages#check_email'
  get 'pages/reset_password_success' => 'pages#reset_password_success'

  namespace :admin do
    root "dashboard#index"
    resources :settings do
    end

    resources :brokerages

    namespace :mls do
      get 'map'
      get 'listings'
    end
  end

  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'

  get "brokerage_dashboard/showings/real_time" => "brokerage_dashboard/showings#real_time", as: "real_time_brokerage_dashboard_showings_path"

  shallow do
    namespace :brokerage_dashboard do
      get '/' => 'dashboard#index'
      resources :brokerage do
        resources :users do
          member do
            get 'reset_password'
          end
          resources :showings do
            resources :sightings
          end
        end
      end
    end
  end

  # resources :showings
  get 's/:id' => 'showings#show', :as => "hidden_showing"


  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations" }



  devise_scope :user do
    post 'registrations' => 'registrations#create', :as => 'register'
    post 'sessions' => 'sessions#create', :as => 'login'
    put 'sessions' => 'sessions#update', :as => 'edit_session'
    delete 'sessions' => 'sessions#destroy', :as => 'logout'
    put 'registrations' => 'registrations#edit', :as => 'edit'
  end

  namespace :api do
    namespace :v1 do
      resources :regions, except: [:new, :edit]
      resources :brokerages, except: [:new, :edit]
      resources :zips#, except: [:new, :edit]
      resources :profiles
      resources :eligible_agents
      resources :showings, except: [:new, :edit]
      resources :leads
      resources :agents#, except: [:new, :edit]
      resources :listings, except: [:new, :edit]
      resources :nearby_agents
      resources :mls
      resources :get_listings
      resources :dev_tokens
    end

    namespace :v2 do
      resources :regions, except: [:new, :edit]
      resources :brokerages, except: [:new, :edit]
      resources :zips#, except: [:new, :edit]
      resources :profiles
      resources :eligible_agents
      resources :showings#, except: [:new, :edit]
      resources :leads
      resources :agents#, except: [:new, :edit]
      resources :listings, except: [:new, :edit]
      resources :nearby_agents
      resources :mls
      resources :get_listings
      resources :dev_tokens
      resources :emergency_contacts
      post 'sightings/heartbeat'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'


  # You can have the root of your site routed with "root"
  root 'main#home'


end

app/controllers/api/v1/showings_controller.rb
class Api::V1::ShowingsController < ApplicationController
  #before_filter :restrict_access
  # GET /showings
  # GET /showings.json
  def index
    if params.has_key?(:buyer_id)
      @showings = Showing.where(buyer_id: "#{params[:buyer_id]}").last
    else
      @showings = Showing.all
    end
    render json: @showings
  end

  # GET /showings/1
  # GET /showings/1.json
  def show
    @showing = Showing.find(params[:id])

    render json: @showing
  end

  # POST /showings
  # POST /showings.json
  def create
    @showing = Showing.new(showing_params)

    if @showing.save
      #update num of showings for this agent
      user = User.find(@showing.agent_id)
      profile = Profile.where(user_id: user.id).last
      num_showings = profile.num_showings
      new_num_showings = num_showings + 1
      profile.update(num_showings: new_num_showings)

      #send push notification
      token = DevToken.where(user_id: @showing.buyer_id).last.dev_token
      notification = Houston::Notification.new(device: token)
      notification.alert = "Your Showing is Starting!"
      notification.badge = 57
      notification.sound = "Turn.aiff"
      notification.content_available = true
      notification.custom_data = {foo: "bar"}
      APN.push(notification)
      PPN.push(notification)

      render json: @showing, status: :created
    else
      render json: @showing.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /showings/1
  # PATCH/PUT /showings/1.json
  def update
    @showing = Showing.find(params[:id])

    if @showing.update(showing_params)
      head :no_content
      if @showing.status == "completed"
        token = DevToken.where(user_id: @showing.buyer_id).last.dev_token
        notification = Houston::Notification.new(device: token)
        notification.alert = "Your Showing is Ending!"
        notification.badge = 0
        notification.sound = "sosumi.aiff"
        notification.content_available = true
        notification.custom_data = {foo: "bar"}
        APN.push(notification)
      end
    else
      render json: @showing.errors, status: :unprocessable_entity
    end
  end

  # DELETE /showings/1
  # DELETE /showings/1.json
  def destroy
    @showing = Showing.find(params[:id])
    @showing.destroy

    head :no_content
  end

  private
  def showing_params
    params.permit(:agent_id, :lead_id, :address, :buyer_name, :agent_name, :buyer_id, :status, :mls_num)
  end

  def restrict_access
    authenticate_or_request_with_http_token do |token, options|
      ApiKey.exists?(access_token: token)
    end
  end
end

app/controllers/api/v2/showings_controller.rb
class Api::V2::ShowingsController < ApplicationController
  #before_filter :restrict_access
  # GET /showings
  # GET /showings.json
  include CurbCall::Messages

  def index
    if params.has_key?(:buyer_id)
      @showings = Showing.where(buyer_id: "#{params[:buyer_id]}").last
    else
      @showings = Showing.all
    end
    render json: @showings
  end

  # GET /showings/1
  # GET /showings/1.json
  def show
    @showing = Showing.find(params[:id])

    render json: @showing
  end

  # POST /showings
  # POST /showings.json
  def create
    @showing = Showing.new(showing_params)

    if @showing.save
      @showing.send_adhoc_stuff(@showing.id)

      #update num of showings for this agent
      user = User.find(@showing.showing_owner_id)#type, should be user_id
      profile = Profile.where(user_id: user.id).last
      num_showings = profile.num_showings
      new_num_showings = num_showings + 1
      profile.update(num_showings: new_num_showings)

      unless @showing.buyer_id.nil?
        agent_id = Agent.where(user_id: @showing.showing_owner_id).last.id

        #push to pusher (on buyer device)
        Pusher.trigger("agent_#{agent_id}", 'showing_status', {:message => 'start_showing'})
      end


      @showing.start

      render json: @showing, status: :created
    else
      render json: @showing.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /showings/1
  # PATCH/PUT /showings/1.json
  def update
    @showing = Showing.find(params[:id])

    #trigger transittion
    #showing.fire_state_event(:shift_up)
    case(showing_params[:agent_state])
    when Showing::STATES[:warning] then @showing.syn_agent
    when Showing::STATES[:danger]
      if(@showing.agent_state == Showing::STATES.fetch(:safe))
        @showing.panic
      else
        @showing.ack_timeout
      end
    when Showing::STATES[:safe] then @showing.syn_ack
    end

    case(showing_params[:status])
    when Showing::SHOWING_STATES[:completed] then @showing.complete
    end


    if @showing.update(showing_params)
      if @showing.status == "completed" && !@showing.buyer_id.nil?
        #push to pusher (on buyer device)
        Agent.where(user_id: @showing.showing_owner).each do |agent|
          Pusher.trigger("agent_#{agent.id}", 'showing_status', {:message => 'end_showing'})
        end

        @showing.send_adhoc_end(@showing.id)
      end

       render json: @showing, status: :ok
    else
       render json: @showing.errors, status: :unprocessable_entity
    end
  end

  # DELETE /showings/1
  # DELETE /showings/1.json
  def destroy
    @showing = Showing.find(params[:id])
    @showing.destroy

    head :no_content
  end

  private
  def showing_params
    params.permit(:showing_owner_id, :showing_owner_type, :lead_id, :address, :buyer_name, :agent_name, :buyer_id, :status, :mls_num, :agent_state, :id, :called, :texted)
  end

  def restrict_access
    authenticate_or_request_with_http_token do |token, options|
      ApiKey.exists?(access_token: token)
    end
  end
end

app/controllers/api/v3/showings_controller.rb
class Api::V3::ShowingsController < Api::V3::ServiceController
  before_filter :authenticate, only: [:create]
  
  def index
  	agent_id = params[:agent_id]
  	@agent = Agent.find_by id: agent_id
  	if !@agent.nil?
  		@brokerage = @agent.brokerage
  		
  		@showings = @agent.user.showings.waiting
  		
  		
		if @showings.any? 
   			#claim this showing
   			return claim_showing(@showings.first, @agent, "User")
		else
			radius = params[:radius] || 10
        	lat = @agent.lat
        	lng = @agent.lon
        	puts "LAT: #{lat} - LONG: #{lng}"
        	origin = Geokit::LatLng.new(lat, lng)
			
			@showings = Showing.within(radius, origin: origin).waiting
			if @showings.any?
				return claim_showing(@showings.first, @agent, "User")
   			end
   		end
   		
   		render json: {errors: ["Could not find any showings at that GPS coord."]}, status: :unprocessable_entity
  	else
  		failure(404, "bad request", "The agent not found")
  	end
  end

  def create
  	params.merge!(brokerage_id: @brokerage.id)
    agent_id = params[:showing_owner_id]
    lat = params[:lat]
    lng = params[:lng]
    radius = params[:radius]
    if params.has_key?(:agent_email)
      agent_email = params[:agent_email]
    else
      agent_email = nil
    end

    @showing = Showing.new(showing_params)
    
    if !@showing.save
    	return failure(405, "bad request", @showing.errors)
    else 

    # get available agents in proximity
    # of will get specified agent if available
    # skip if this is an adhoc showing (radius app)
    if params[:status] == "started"
      @showing.status="started"
      @showing.showing_owner_id = params[:showing_owner_id]
      @showing.showing_owner_type = params[:showing_owner_type]
    else
      #Tenp disabled. Fix this (TO DO)
      disptacher = CurbCall::DispatchService::Dispatcher.new(@showing)
      agents = disptacher.find_agents({lat: lat, lng: lng, radius: radius, agent_id: agent_id, sandbox: false, agent_email: agent_email})

      if(agents.any?)
        disptacher.notify_agents(@showing, agents)

        ## TEMP FIX:
=begin
        agents.each do |agent|
          agent.new_request
          data = { alert: "You've Been Requested!", sound: "sosumi.aiff", message: 'request', showing_id: @showing.id}
          #data.merge!(opts)
          #user_id = Agent.find(params[:agent_id]).user_id
          user_id = Agent.find(agent.id).user_id
          push = Parse::Push.new(data)
          query = Parse::Query.new(Parse::Protocol::CLASS_INSTALLATION).eq('user_id', user_id)
          push.where = query.where
          push.save
        end
=end

      else # no agents found
        @showing.errors.add("errors", "Could not find any agents at that GPS coord.")
      end


      #if we are in sandbox, auto attach an agent
      # if @sandbox
      #   temp_agent = agents.first
      #   @showing.showing_owner_id = temp_agent.user_id
      #   @showing.agent_name = temp_agent.name
      #   @showing.attach_agent
      # end
    end


    if @showing.errors.empty? && @showing.save
      render json: @showing, status: :created
    else
      render json: @showing.errors, status: :unprocessable_entity
    end
    
    end
  end

  def show
    @showing = Showing.find(params[:id])

    render json: @showing

  end

  # Endpoint for agents to claim this showing
  def claim
    id = params[:id]
    agent_id = params[:agent_id]

    @agent = Agent.find(agent_id)
    @showing = Showing.find(id)
    claim_showing(@showing, @agent, params[:showing_owner_type])
  end

  def start
    id = params[:id]

    @showing = Showing.find(id)
    @showing.start

    if @showing.errors.empty? && @showing.save
      render json: @showing
    else
      render json: @showing.errors, status: :unprocessable_entity
    end

  end

  def self_start
    @showing = Showing.create(
    showing_owner_id:params[:showing_owner_id],
    agent_name:params[:agent_name],
    status:"started",
    showing_owner_type:"User")

    @showing.start

    if @showing.errors.empty? && @showing.save
      render json: @showing
    else
      render json: @showing.errors, status: :unprocessable_entity
    end
  end

  def end
    id = params[:id]

    @showing = Showing.find(id)
    @showing.complete

    if @showing.errors.empty? && @showing.save
      render json: @showing
    else
      render json: @showing.errors, status: :unprocessable_entity
    end

  end

  # api/v3/showings/:id/
  def update
    id = params[:id]
    @showing = Showing.find(id)
    @showing.transition!(params[:showing][:agent_state])
   

    if @showing.save && @showing.errors.empty?
      render json: @showing
    else
      render json: @showing.errors, status: :unprocessable_entity
    end
  end



  private
  
  def authenticate_token
  	authenticate_with_http_token do |token, options|
  		@brokerage = Brokerage.find_by(access_token: token)
  	end
  end
  
  def showing_params
    params.permit(:lat, :lng, :brokerage_id, :buyer_name, :buyer_phone, :buyer_email, :hood, :address, :address_two, :photo_url, :list_price, :notes, :status, :agent_state, :called, :texted )
  end
  
  def failure(code, info, message)
    render :status => code,
           :json => { :success => false,
                      :info => info,
                      :data => {message: message} }
  end
  
  def claim_showing(showing, agent, showing_owner_type="User")
  	showing.showing_owner_id = agent.user_id
    showing.showing_owner_type = showing_owner_type
    showing.agent_name  = agent.name
    showing.attach_agent

    if showing.save && showing.errors.empty?
      render json: showing
    else
      render json: showing.errors, status: :unprocessable_entity
    end
  end

end

app/controllers/brokerage_dashboard/dashboard_controller.rb
class BrokerageDashboard::DashboardController < ApplicationController
	before_filter :authenticate_user!
  before_filter :set_brokerage
  layout 'dashboard'
  
  def index
    #get brokerage showings for today
    today=Time.zone.today
    start_date=today.beginning_of_day
    week_start_date=today.beginning_of_week
    month_start_date=today.beginning_of_month
    end_date=today.end_of_day
    
    @showings=@brokerage.showings_request.for_range(start_date, end_date).waiting#.includes(:sightings)
    @showings_this_week=@brokerage.showings.for_range(week_start_date, end_date)
    @showings_this_month=@brokerage.showings.for_range(month_start_date, end_date)
    
    @active_showings = @brokerage.showings.active.reject{|showing|showing.sightings.empty?}
  end
  
  private
  def set_brokerage
    if current_user.brokerage
      @brokerage = current_user.brokerage
    else
      redirect_to root_path, notice: 'This user does not belong to a brokerage.'
    end
  end

  # def index
  #   # if current_user.office_admin == "true"
  #     @users = User.all
  #     @agents = User.where(brokerage_id: current_user.brokerage_id)
  #     @live_agents = Agent.where(brokerage_id: current_user.brokerage_id)
  #     @brokerage = Brokerage.find(current_user.brokerage_id)
  #     @showings = Showing.all
  #
  #     #@buyers = User.where(id: )
  #
  #     # @showing_now = Array.new
  #     # Showing.where(status: nil).each do |showing|
  #     #   if User.find(showing.agent_id).exists?
  #     #     agent = User.find(showing.agent_id)
  #     #   else
  #     #     agent = 100000000000000000
  #     #   end
  #
  #     #   if agent.brokerage_id == @brokerage.id
  #     #     @showing_now << agent
  #     #   end
  #     # end
  #
  #   # else
  #   #   redirect_to login_path
  #   # end
  #     # @json = @live_agents.to_gmaps4rails
  #    #      @markers = @live_agents.to_gmaps4rails
  # end
  #
  # def show
  #   @agent = User.find(params[:id])
  #   @available = Agent.where(user_id: @agent.id).any?
  # end
end

app/controllers/showings_controller.rb
class ShowingsController < ApplicationController
  acts_as_token_authentication_handler_for User, except: [:show]
  def show
    id = ScatterSwap.reverse_hash(params[:id])
    @showing = Showing.find(id)
    @sightings = @showing.sightings
  end
end

app/views/brokerage_dashboard/showings/_form.html.haml
= form_for @showing do |f|
  - if @showing.errors.any?
    #error_explanation
      %h2= "#{pluralize(@showing.errors.count, "error")} prohibited this showing from being saved:"
      %ul
        - @showing.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :agent
    = f.text_field :agent
  .field
    = f.label :lead
    = f.text_field :lead
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :buyer_name
    = f.text_field :buyer_name
  .field
    = f.label :agent_name
    = f.text_field :agent_name
  .field
    = f.label :buyer_id
    = f.text_field :buyer_id
  .field
    = f.label :status
    = f.text_field :status
  .field
    = f.label :mls_num
    = f.text_field :mls_num
  .actions
    = f.submit 'Save'

app/views/brokerage_dashboard/showings/_rt_map.html.haml
.ibox
  .ibox-title
    %h5 Real-time Showing Map
  .ibox-content
    %p
      This map shows all showings that are currently in progress. Sightings on the real-time map are updated every 5 minutes.
    #rt-map-canvas.googmap_square
      .middle-box.text-center.animated.fadeInRightBig
        %h3.font-bold No showings yet
        .error-desc
          There have been no showings today using Curb Call. When one of your agents finishes a showing
          it will show up on the map here.
          %br/
    
#info-tmpl.hidden
  .contact-box
    .col-sm-3
      .text-center
        %img.img-circle.m-t-xs.img-responsive{src:"{{profile_img_url}}", width:110}
    .col-sm-8
      %h3
        %strong {{name}}
      %p
        %i.fa.fa-map-marker
        {{latlng}}
      %p{class:"{{show_warning}}"}
        %span.label.label-warning Non-Responsive
      %p
        %strong Last Contact: 
        %span {{last_sighting_elapsed}}
      %address
        %strong Elapsed Time: {{elapsed}}
        %br/
        {{{address}}}
        %br/
        %abbr{:title => "Phone"} P:
        (123) 456-7890
      %dl
        %dt Consumer Name:
        %dd {{buyer_name}}
        %dt MLS Num:
        %dd {{mls_num}}
      %p
        %a{href:"{{details_link}}"}
          View Extended Details
    .clearfix
    
:javascript
  var showings = []
  showings = #{@active_showings.to_json({include: {sightings:{}, showing_owner:{include: :profile}}, methods:[:time_length] }) }

app/views/brokerage_dashboard/showings/edit.html.haml
%h1 Editing showing

= render 'form'

= link_to 'Show', @showing
\|
= link_to 'Back', showings_path

app/views/brokerage_dashboard/showings/index.html.haml
.table-wrapper.orders-table.section
  .row.head
    .col-md-12
      %h4 Showings
  .row.filter-block
    .pull-right
      .btn-group.pull-right
        %button.glow.left.large{:onclick=>"all_showings()"} All
        %button.glow.middle.large{:onclick=>"pending_showings()"} Pending
        %button.glow.right.large{:onclick=>"completed_showings()"} Completed
      %input.search.order-search{:placeholder => "Search for an showing..", :type => "text", :onkeydown => "search_showings(event)", :value=>@search}/
  .row
    %table.table.table-hover
      %thead
        %tr
          %th.col-md-1
            Showing ID
          %th.col-md-1
            %span.line
            Date
          %th.col-md-1
            %span.line
            Consumer
          %th.col-md-1
            %span.line
            Consumer Email
          %th.col-md-2
            %span.line
            Property Address
          %th.col-md-1
            %span.line
            Agent
          %th.col-md-1
            %span.line
            Latitude
          %th.col-md-1
            %span.line
            Longitude
          %th.col-md-1
            %span.line
            Duration
          %th.col-md-1
            %span.line
            Showing State
      %tbody
        / row
        - @showings.each do |showing|
          %tr
            %td
              =link_to "##{showing.id}", brokerage_dashboard_showing_path(showing)
            %td=showing.created_at.strftime("%a %b %d %Y")
            %td=showing.buyer_name
            %td=showing.buyer_email
            %td=showing.address
            %td=showing.agent_name_completed_with_email
            %td=showing.lat
            %td=showing.lng
            %td="#{showing.time_length.to_i} Minutes"
            %td
              %span{class:"label label-#{badge_helper_showing(showing.status.to_s)}", style: "font-weight: bold"}
                =showing.status.to_s
  = paginate @showings
  
:javascript
  var url = "#{brokerage_dashboard_user_showings_path(current_user)}?page=0";
  
  function params_showings(){
    return "&search=" + $(".search.order-search").val();
  }
  
  function general_showings(extra_params){
    extra_params = (extra_params==null || extra_params== undefined) ? '' : extra_params;
    document.location.href = url + params_showings() + extra_params;
  }
  
  function all_showings(){
    general_showings('');
  }
  
  function pending_showings(){
    general_showings("&status_state_search=waiting");
  }
  
  function completed_showings(){
    general_showings("&status_state_search=completed");
  }
  
  function search_showings(event){
    if (event.keyCode == 13)
      general_showings();
  }

app/views/brokerage_dashboard/showings/new.html.haml
%h1 New showing

= render 'form'

= link_to 'Back', showings_path

app/views/brokerage_dashboard/showings/real_time.html.haml
%script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyAJfjOMKoBPVPs7u4wdrlhsUlcvsDKsUhE", :type => "text/javascript"}

.row
  .col-md-6
    =render 'rt_map'
  .col-md-6
    .ibox
      .ibox-title
        %h5 Showings Details
      .ibox-content
        %p
          %b Active Showings:
          =@active_showings.count



%p#notice= notice



:javascript
  var page_id = "showings#real_time"

app/views/brokerage_dashboard/showings/show.html.haml
%script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyAJfjOMKoBPVPs7u4wdrlhsUlcvsDKsUhE&libraries=geometry", :type => "text/javascript"}

.row
  .col-md-6
    .ibox
      .ibox-title
        %h5 Sightings Map
        %span.beacon
          %span.ring
          %span.dot
      .ibox-content
        %p
          This is the location history of the showing. If the showing is still in progress, the current location on the map (red pin) will be
          automaticly updated.
        #map-canvas.googmap_square
          .middle-box.text-center.animated.fadeInRightBig
            %h3.font-bold No sightings yet
            .error-desc
              When an agent begins a showing, a heart-beat pulse will be sent from their phone every few seconds. However, in this case
              we have not yet received any heartbeats from this agents phone. 
              %br/
  .col-md-6
    .ibox
      .ibox-title
        %h5 Showings Details
      .ibox-content
        %p
          %b Agent:
          = @showing.agent_name_completed
        %p
          %b Address:
          = @showing.address
        %p
          %b Buyer name:
          = @showing.buyer_name
        %p
          %b Agent name:
          = @showing.agent_name
        %p
          %b Status:
          = @showing.agent_state
        %p
          %b Mls num:
          = @showing.mls_num
        %p
          %b Sighting Count:
          = @showing.sightings.count
        -if @showing.sightings.length > 0
          %p
            %b Last Contact:
            ="#{@showing.sightings.last.created_at.strftime("%a %b %d %Y")} (#{distance_of_time_in_words(@showing.sightings.last.created_at, Time.zone.now)} ago)"
        %p
          %b Showing Length:
          =@showing.time_length.to_i
          Minutes
        %p
          %b Date:
          = @showing.created_at.strftime("%a %b %d %Y")
        %p
          %b Showing State:
          = @showing.status
        %p
          %b Called:
          = @showing.called.to_s.capitalize	 
        %p
          %b Texted:
          = @showing.texted.to_s.capitalize	 		   
    .ibox
      .ibox-title
        %h5 History
      .ibox-content
        %ul.list-group.clear-list.m-t
          -@showing.history.all.each_with_index do |event,i|
            %li.list-group-item.fist-item
              %span.pull-right
                ="#{event[:ts].strftime("%I:%M %p")}"
              %span.label.label-success=i 
              ="#{CurbCall::SafetyRadius::History::MESSAGES[event[:event].to_sym]}"           
          



  :cdata
:javascript
  var page_id = "showing#show"
  var showing = #{@showing.to_json({include: :sightings})}


%p#notice= notice



= link_to 'Back', brokerage_dashboard_user_showings_path(@user)

app/views/brokerage_dashboard/showings/showing_show.html.haml
  
.asdf
  %h1
    Listings demo map
#map-canvas

:css
  #map-canvas { height: 700px; margin: 0; padding: 0;}
%script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyAJfjOMKoBPVPs7u4wdrlhsUlcvsDKsUhE&libraries=geometry", :type => "text/javascript"}

  :cdata
:javascript
  var points = #{@sightings.to_json}
:javascript
  function initialize() {
    var mapOptions = {
      center: { lat: 32.7451599752403, lng: -117.137919347596},
      zoom: 8
    };
    var map = new google.maps.Map(document.getElementById('map-canvas'),
        mapOptions);
    
    var flightPlanCoordinates=[];
    for (i=0; i<points.length; i++)
    {
      flightPlanCoordinates.push(new google.maps.LatLng(points[i]['lat'], points[i]['lon']));
    }
    
    var flightPath = new google.maps.Polyline({
      path: flightPlanCoordinates,
      geodesic: true,
      strokeColor: '#FF0000',
      strokeOpacity: 1.0,
      strokeWeight: 2
    });
    
    flightPath.setMap(map);
  }
  google.maps.event.addDomListener(window, 'load', initialize);