config/routes.rb
CurbApi::Application.routes.draw do

  mount_griddler
  
  namespace :developers do
    devise_for :developers, module: "developers/devise", path: "developer"
    root 'dashboard#index'
    resources :apps
    get 'api' => 'api#index'
    get 'api/:action' => 'api#index', as: "api_doc"
  end

  namespace :api do
    namespace :v3 do
      get 'agents/find'
      get 'agents' => "agents#index"
      get 'service/index'
      get 'organization/showing_report' => "organization#showing_report", as: :api_v3_organization_showing_report
      resources :agents do
      	resources :showings, only: [:index]
      end
      resources :users   
      resources :showings do
        member do
          post 'claim'
          post 'start'
          post 'end'
          post 'self_start'
        end
      end
      namespace :radius do
        get 'client_token' => "braintree#client_token"
        post 'subscriptions' => "braintree#subscriptions"
        devise_for :radius_users
        resources :users do
          resources :emergency_contacts
        end
      end
    end
  end

  get 'main/home'
  get 'pages/check_email' => 'pages#check_email'
  get 'pages/reset_password_success' => 'pages#reset_password_success'

  namespace :admin do
    root "dashboard#index"
    resources :settings do
    end

    resources :brokerages

    namespace :mls do
      get 'map'
      get 'listings'
    end
  end

  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'

  get "brokerage_dashboard/showings/real_time" => "brokerage_dashboard/showings#real_time", as: "real_time_brokerage_dashboard_showings_path"

  shallow do
    namespace :brokerage_dashboard do
      get '/' => 'dashboard#index'
      resources :brokerage do
        resources :users do
          member do
            get 'reset_password'
          end
          resources :showings do
            resources :sightings
          end
        end
      end
    end
  end

  # resources :showings
  get 's/:id' => 'showings#show', :as => "hidden_showing"


  devise_for :users, controllers: { sessions: "users/sessions", passwords: "users/passwords", registrations: "users/registrations" }



  devise_scope :user do
    post 'registrations' => 'registrations#create', :as => 'register'
    post 'sessions' => 'sessions#create', :as => 'login'
    put 'sessions' => 'sessions#update', :as => 'edit_session'
    delete 'sessions' => 'sessions#destroy', :as => 'logout'
    put 'registrations' => 'registrations#edit', :as => 'edit'
  end

  namespace :api do
    namespace :v1 do
      resources :regions, except: [:new, :edit]
      resources :brokerages, except: [:new, :edit]
      resources :zips#, except: [:new, :edit]
      resources :profiles
      resources :eligible_agents
      resources :showings, except: [:new, :edit]
      resources :leads
      resources :agents#, except: [:new, :edit]
      resources :listings, except: [:new, :edit]
      resources :nearby_agents
      resources :mls
      resources :get_listings
      resources :dev_tokens
    end

    namespace :v2 do
      resources :regions, except: [:new, :edit]
      resources :brokerages, except: [:new, :edit]
      resources :zips#, except: [:new, :edit]
      resources :profiles
      resources :eligible_agents
      resources :showings#, except: [:new, :edit]
      resources :leads
      resources :agents#, except: [:new, :edit]
      resources :listings, except: [:new, :edit]
      resources :nearby_agents
      resources :mls
      resources :get_listings
      resources :dev_tokens
      resources :emergency_contacts
      post 'sightings/heartbeat'
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'


  # You can have the root of your site routed with "root"
  root 'main#home'


end

app/models/brokerage.rb
class Brokerage < ActiveRecord::Base

	has_many :users, dependent: :destroy
	has_many :agents, dependent: :destroy
	has_many :showings, through: :users
	has_many :showings_request, class_name: "Showing"

	has_and_belongs_to_many :mls, join_table: :mls_brokerages, dependent: :destroy
	has_and_belongs_to_many :zips, join_table: :brokerage_zips, dependent: :destroy

	accepts_nested_attributes_for :users

	before_create :gen_token
	after_create :generate_lead_email


	private

	def gen_token
		self.access_token = SecureRandom.hex(20)
	end

	def generate_lead_email
		random_token = generate_random_token
		if email_token_is_used?(random_token)
			while email_token_is_used?(random_token)
			 random_token = generate_random_token
			end
		else
			self.update(lead_email: random_token+"@curbcallcollect.com")
		end
	end

	def generate_random_token
		SecureRandom.urlsafe_base64(nil, false).downcase
	end

	def email_token_is_used?(random_token)
		Brokerage.where(lead_email: random_token).count >= 1
	end
end

app/controllers/admin/brokerages_controller.rb
class Admin::BrokeragesController < ApplicationController
    layout 'admin'
    respond_to :html
    
    before_action :set_brokerage, only: [:show, :edit, :update]
    
    def index
      @brokerages = Brokerage.all
    end
    
    def show
    end
    
    def new
      @brokerage = Brokerage.new
      build_default_agent
    end
    
    def edit
      if @brokerage.users.any?
        @default_agent = @brokerage.users.first
      else
        build_default_agent
      end
    end
    
    def create
      @brokerage = Brokerage.new(brokerage_params)
      
	  if @brokerage.save
		respond_with(:admin, @brokerage)
	  else
		respond_using(:admin, @brokerage, :new)
	  end
    end
    
    def update
      if @brokerage.update(brokerage_params)
  		respond_with(:admin, @brokerage)
  	  else
  		respond_using(:admin, @brokerage, :edit)
	  end
    end
    
    private
    
    def brokerage_params
      params.require(:brokerage).permit(:name, users_attributes: [:id, :email, :name, :password, :password_confirmation])
    end
    
    def set_brokerage
      @brokerage = Brokerage.find_by id: params[:id]
    end
    
    def build_default_agent
      @default_agent = @brokerage.users.build
    end
    
end

app/controllers/api/v1/brokerages_controller.rb
class Api::V1::BrokeragesController < ApplicationController
  #before_filter :restrict_access
  # GET /brokerages
  # GET /brokerages.json
  def index
    @brokerages = Brokerage.all

    render json: @brokerages
  end

  # GET /brokerages/1
  # GET /brokerages/1.json
  def show
    @brokerage = Brokerage.find(params[:id])

    render json: @brokerage
  end

  # POST /brokerages
  # POST /brokerages.json
  def create
    @brokerage = Brokerage.new(params[:brokerage])

    if @brokerage.save
      render json: @brokerage, status: :created
    else
      render json: @brokerage.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /brokerages/1
  # PATCH/PUT /brokerages/1.json
  def update
    @brokerage = Brokerage.find(params[:id])

    if @brokerage.update(params[:brokerage])
      head :no_content
    else
      render json: @brokerage.errors, status: :unprocessable_entity
    end
  end

  # DELETE /brokerages/1
  # DELETE /brokerages/1.json
  def destroy
    @brokerage = Brokerage.find(params[:id])
    @brokerage.destroy

    head :no_content
  end

  private
  def restrict_access
    authenticate_or_request_with_http_token do |token, options|
      ApiKey.exists?(access_token: token)
    end
  end
end

app/controllers/api/v2/brokerages_controller.rb
class Api::V2::BrokeragesController < ApplicationController
  #before_filter :restrict_access
  # GET /brokerages
  # GET /brokerages.json
  def index
    @brokerages = Brokerage.all

    render json: @brokerages
  end

  # GET /brokerages/1
  # GET /brokerages/1.json
  def show
    @brokerage = Brokerage.find(params[:id])

    render json: @brokerage
  end

  # POST /brokerages
  # POST /brokerages.json
  def create
    @brokerage = Brokerage.new(params[:brokerage])

    if @brokerage.save
      render json: @brokerage, status: :created
    else
      render json: @brokerage.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /brokerages/1
  # PATCH/PUT /brokerages/1.json
  def update
    @brokerage = Brokerage.find(params[:id])

    if @brokerage.update(params[:brokerage])
      head :no_content
    else
      render json: @brokerage.errors, status: :unprocessable_entity
    end
  end

  # DELETE /brokerages/1
  # DELETE /brokerages/1.json
  def destroy
    @brokerage = Brokerage.find(params[:id])
    @brokerage.destroy

    head :no_content
  end

  private
  def restrict_access
    authenticate_or_request_with_http_token do |token, options|
      ApiKey.exists?(access_token: token)
    end
  end
end

app/views/admin/brokerages/_form.html.haml
.row.form-wrapper
  / left column
  .col-md-9.with-sidebar
    = form_for [:admin, @brokerage], html: { class: "form-horizontal"} do |f|
      - if @brokerage.errors.any?
        #error_explanation
          %h2= "#{pluralize(@brokerage.errors.count, "error")} prohibited this setting from being saved:"
          %ul
            - @brokerage.errors.full_messages.each do |msg|
              %li= msg
      
      .form-group
        %label.col-md-2.control-label{:for => "inputName1"}= "Name"
        .col-md-8
          =f.text_field :name, class: "form-control",:placeholder => "Value", :type => "text"
          
      #pad-wrapper.new-user{:style=>"margin: 15px;"}
        .row.header{:style=>"margin-bottom: 0px;"}
          .col-md-12
            %h3 Default Agent
          .row.form-wrapper{:style=>"margin-bottom: 0px;"}
            / left column
            .col-md-9.with-sidebar
              = f.fields_for :users, @default_agent do |user|
                .form-group
                  %label.col-md-2.control-label{:for => "inputName1"} Name
                  .col-md-8
                    =user.text_field :name, class: "form-control",:placeholder => "Name", :type => "text"
                  
                .form-group
                  %label.col-md-2.control-label{:for => "inputEmail1"} Email
                  .col-md-8
                    =user.text_field :email, class: "form-control",:placeholder => "Email", :type => "text"
                    
                .form-group
                  %label.col-md-2.control-label{:for => "inputPassword1"} Password
                  .col-md-8
                    =user.text_field :password, class: "form-control",:placeholder => "Password  ", :type => "password", :autocomplete=>"false"
                  
      .form-group
        .col-md-offset-2.col-md-8
          = f.submit 'Save', class: "btn-glow primary"

app/views/admin/brokerages/edit.html.haml
%h1 Editing brokerage
%br

= render 'form'

= link_to 'Show',admin_brokerage_path(@brokerage)
\|
= link_to 'Back', admin_brokerages_path

app/views/admin/brokerages/index.html.haml
.table-wrapper.products-table.section
  .row.head
    .col-md-12
      %h4 Brokerages
  .row.filter-block
    .pull-right
      %a.btn-flat.success.new-product{:href=>new_admin_brokerage_path} + Add Brokerage
  .row
    %table.table.table-hover
      %thead
        %tr
          %th.col-md-3
            Name
          %th.col-md-3
            %span.line>
            Token
          %th.col-md-3
      %tbody
        -@brokerages.each do |b|
          %tr
            %td
              %a.name{:href => admin_brokerage_path(b)}=b.name
            %td.description=b.access_token
            %td
              %ul.actions
                %li
                  =link_to "Edit", edit_admin_brokerage_path(b) 
                %li.last
                  %a{:href => "#"} Delete

app/views/admin/brokerages/new.html.haml
%h1 Creating brokerage
%br

= render 'form'

= link_to 'Back', admin_brokerages_path

app/views/admin/brokerages/show.html.haml
.row
  .col-md-6
    .ibox
      .ibox-title
        %h4 Brokerage Details
        %br
      .ibox-content
        %p
          %b Name:
          = @brokerage.name
        %p
          %b Token:
          = @brokerage.access_token
          
        %p
          %b Default Agent:
          = @brokerage.users.first.name

= link_to 'Back', admin_brokerages_path